@baseUrl = http://localhost:3000

### Request 0 : GetAllUsers
GET {{baseUrl}}/users

### Request 1 : CreateOneUser
POST {{baseUrl}}/users/create
content-type: application/json

{
    "username": "12 Jhon",
    "password": "121212"
}

### Request 2 : GetAllUsers
GET {{baseUrl}}/users/1


### Request 3 : UpdateOneUser
PUT {{baseUrl}}/users/1
content-type: application/json

{
    "username": "1_hon",
    "password": "121212"
}